; Generated by tools/gentext.py from work/script.json (items, techs, enemies):
; the full-length names, a pointer per record (ext/longnames.asm). Do not edit.
LN_Items_N = 128
LN_Items:
	dc.l	LNS_items_000, LNS_items_001, LNS_items_002, LNS_items_003, LNS_items_004, LNS_items_005, LNS_items_006, LNS_items_007
	dc.l	LNS_items_008, LNS_items_009, LNS_items_010, LNS_items_011, LNS_items_012, LNS_items_013, LNS_items_014, LNS_items_015
	dc.l	LNS_items_016, LNS_items_017, LNS_items_018, LNS_items_019, LNS_items_020, LNS_items_021, LNS_items_022, LNS_items_023
	dc.l	LNS_items_024, LNS_items_025, LNS_items_026, LNS_items_027, LNS_items_028, LNS_items_029, LNS_items_030, LNS_items_031
	dc.l	LNS_items_032, LNS_items_033, LNS_items_034, LNS_items_035, LNS_items_036, LNS_items_037, LNS_items_038, LNS_items_039
	dc.l	LNS_items_040, LNS_items_041, LNS_items_042, LNS_items_043, LNS_items_044, LNS_items_045, LNS_items_046, LNS_items_047
	dc.l	LNS_items_048, LNS_items_049, LNS_items_050, LNS_items_051, LNS_items_052, LNS_items_053, LNS_items_054, LNS_items_055
	dc.l	LNS_items_056, LNS_items_057, LNS_items_058, LNS_items_059, LNS_items_060, LNS_items_061, LNS_items_062, LNS_items_063
	dc.l	LNS_items_064, LNS_items_065, LNS_items_066, LNS_items_067, LNS_items_068, LNS_items_069, LNS_items_070, LNS_items_071
	dc.l	LNS_items_072, LNS_items_073, LNS_items_074, LNS_items_075, LNS_items_076, LNS_items_077, LNS_items_078, LNS_items_079
	dc.l	LNS_items_080, LNS_items_081, LNS_items_082, LNS_items_083, LNS_items_084, LNS_items_085, LNS_items_086, LNS_items_087
	dc.l	LNS_items_088, LNS_items_089, LNS_items_090, LNS_items_091, LNS_items_092, LNS_items_093, LNS_items_094, LNS_items_095
	dc.l	LNS_items_096, LNS_items_097, LNS_items_098, LNS_items_099, LNS_items_100, LNS_items_101, LNS_items_102, LNS_items_103
	dc.l	LNS_items_104, LNS_items_105, LNS_items_106, LNS_items_107, LNS_items_108, LNS_items_109, LNS_items_110, LNS_items_111
	dc.l	LNS_items_112, LNS_items_113, LNS_items_114, LNS_items_115, LNS_items_116, LNS_items_117, LNS_items_118, LNS_items_119
	dc.l	LNS_items_120, LNS_items_121, LNS_items_122, LNS_items_123, LNS_items_124, LNS_items_125, LNS_items_126, LNS_items_127
LN_Techs_N = 64
LN_Techs:
	dc.l	LNS_techs_000, LNS_techs_001, LNS_techs_002, LNS_techs_003, LNS_techs_004, LNS_techs_005, LNS_techs_006, LNS_techs_007
	dc.l	LNS_techs_008, LNS_techs_009, LNS_techs_010, LNS_techs_011, LNS_techs_012, LNS_techs_013, LNS_techs_014, LNS_techs_015
	dc.l	LNS_techs_016, LNS_techs_017, LNS_techs_018, LNS_techs_019, LNS_techs_020, LNS_techs_021, LNS_techs_022, LNS_techs_023
	dc.l	LNS_techs_024, LNS_techs_025, LNS_techs_026, LNS_techs_027, LNS_techs_028, LNS_techs_029, LNS_techs_030, LNS_techs_031
	dc.l	LNS_techs_032, LNS_techs_033, LNS_techs_034, LNS_techs_035, LNS_techs_036, LNS_techs_037, LNS_techs_038, LNS_techs_039
	dc.l	LNS_techs_040, LNS_techs_041, LNS_techs_042, LNS_techs_043, LNS_techs_044, LNS_techs_045, LNS_techs_046, LNS_techs_047
	dc.l	LNS_techs_048, LNS_techs_049, LNS_techs_050, LNS_techs_051, LNS_techs_052, LNS_techs_053, LNS_techs_054, LNS_techs_055
	dc.l	LNS_techs_056, LNS_techs_057, LNS_techs_058, LNS_techs_059, LNS_techs_060, LNS_techs_061, LNS_techs_062, LNS_techs_063
LN_Enemies_N = 127
LN_Enemies:
	dc.l	LNS_enemies_000, LNS_enemies_001, LNS_enemies_002, LNS_enemies_003, LNS_enemies_004, LNS_enemies_005, LNS_enemies_006, LNS_enemies_007
	dc.l	LNS_enemies_008, LNS_enemies_009, LNS_enemies_010, LNS_enemies_011, LNS_enemies_012, LNS_enemies_013, LNS_enemies_014, LNS_enemies_015
	dc.l	LNS_enemies_016, LNS_enemies_017, LNS_enemies_018, LNS_enemies_019, LNS_enemies_020, LNS_enemies_021, LNS_enemies_022, LNS_enemies_023
	dc.l	LNS_enemies_024, LNS_enemies_025, LNS_enemies_026, LNS_enemies_027, LNS_enemies_028, LNS_enemies_029, LNS_enemies_030, LNS_enemies_031
	dc.l	LNS_enemies_032, LNS_enemies_033, LNS_enemies_034, LNS_enemies_035, LNS_enemies_036, LNS_enemies_037, LNS_enemies_038, LNS_enemies_039
	dc.l	LNS_enemies_040, LNS_enemies_041, LNS_enemies_042, LNS_enemies_043, LNS_enemies_044, LNS_enemies_045, LNS_enemies_046, LNS_enemies_047
	dc.l	LNS_enemies_048, LNS_enemies_049, LNS_enemies_050, LNS_enemies_051, LNS_enemies_052, LNS_enemies_053, LNS_enemies_054, LNS_enemies_055
	dc.l	LNS_enemies_056, LNS_enemies_057, LNS_enemies_058, LNS_enemies_059, LNS_enemies_060, LNS_enemies_061, LNS_enemies_062, LNS_enemies_063
	dc.l	LNS_enemies_064, LNS_enemies_065, LNS_enemies_066, LNS_enemies_067, LNS_enemies_068, LNS_enemies_069, LNS_enemies_070, LNS_enemies_071
	dc.l	LNS_enemies_072, LNS_enemies_073, LNS_enemies_074, LNS_enemies_075, LNS_enemies_076, LNS_enemies_077, LNS_enemies_078, LNS_enemies_079
	dc.l	LNS_enemies_080, LNS_enemies_081, LNS_enemies_082, LNS_enemies_083, LNS_enemies_084, LNS_enemies_085, LNS_enemies_086, LNS_enemies_087
	dc.l	LNS_enemies_088, LNS_enemies_089, LNS_enemies_090, LNS_enemies_091, LNS_enemies_092, LNS_enemies_093, LNS_enemies_094, LNS_enemies_095
	dc.l	LNS_enemies_096, LNS_enemies_097, LNS_enemies_098, LNS_enemies_099, LNS_enemies_100, LNS_enemies_101, LNS_enemies_102, LNS_enemies_103
	dc.l	LNS_enemies_104, LNS_enemies_105, LNS_enemies_106, LNS_enemies_107, LNS_enemies_108, LNS_enemies_109, LNS_enemies_110, LNS_enemies_111
	dc.l	LNS_enemies_112, LNS_enemies_113, LNS_enemies_114, LNS_enemies_115, LNS_enemies_116, LNS_enemies_117, LNS_enemies_118, LNS_enemies_119
	dc.l	LNS_enemies_120, LNS_enemies_121, LNS_enemies_122, LNS_enemies_123, LNS_enemies_124, LNS_enemies_125, LNS_enemies_126
LNS_items_000:
	dc.b	$C4
LNS_items_001:
	dc.b	$1D, $17, $0B, $16, $16, $00, $15, $0F, $23, $C4
LNS_items_002:
	dc.b	$0E, $23, $18, $0B, $17, $13, $1E, $0F, $C4
LNS_items_003:
	dc.b	$15, $0F, $23, $00, $1E, $1F, $0C, $0F, $C4
LNS_items_004:
	dc.b	$17, $0B, $1C, $1F, $0F, $1C, $0B, $11, $1F, $17, $C4
LNS_items_005:
	dc.b	$11, $1C, $0F, $0F, $18, $00, $0D, $0B, $1C, $0E, $C4
LNS_items_006:
	dc.b	$0C, $16, $1F, $0F, $00, $0D, $0B, $1C, $0E, $C4
LNS_items_007:
	dc.b	$23, $0F, $16, $16, $19, $21, $0D, $0B, $1C, $0E, $C4
LNS_items_008:
	dc.b	$1C, $0F, $0E, $00, $0D, $0B, $1C, $0E, $C4
LNS_items_009:
	dc.b	$16, $0F, $1E, $1E, $0F, $1C, $C4
LNS_items_010:
	dc.b	$1C, $0F, $0D, $19, $1C, $0E, $0F, $1C, $C4
LNS_items_011:
	dc.b	$17, $1C, $1F, $1C, $0B, $00, $16, $0F, $0B, $10, $C4
LNS_items_012:
	dc.b	$1A, $16, $0B, $1D, $17, $0B, $1C, $13, $18, $11, $C4
LNS_items_013:
	dc.b	$1A, $1C, $13, $1D, $17, $C4
LNS_items_014:
	dc.b	$1E, $0F, $16, $0F, $1A, $13, $1A, $0F, $C4
LNS_items_015:
	dc.b	$0F, $1D, $0D, $0B, $1A, $13, $1A, $0F, $C4
LNS_items_016:
	dc.b	$12, $13, $0E, $0B, $1A, $13, $1A, $0F, $C4
LNS_items_017:
	dc.b	$17, $19, $18, $19, $17, $0B, $1E, $0F, $C4
LNS_items_018:
	dc.b	$0E, $13, $17, $0B, $1E, $0F, $C4
LNS_items_019:
	dc.b	$1E, $1C, $13, $17, $0B, $1E, $0F, $C4
LNS_items_020:
	dc.b	$0B, $18, $1E, $13, $0E, $19, $1E, $0F, $C4
LNS_items_021:
	dc.b	$1D, $1E, $0B, $1C, $00, $17, $13, $1D, $1E, $C4
LNS_items_022:
	dc.b	$17, $19, $19, $18, $00, $0E, $0F, $21, $C4
LNS_items_023:
	dc.b	$12, $0F, $0B, $0E, $11, $0F, $0B, $1C, $C4
LNS_items_024:
	dc.b	$1C, $13, $0C, $0C, $19, $18, $C4
LNS_items_025:
	dc.b	$10, $13, $0C, $0F, $1C, $11, $0F, $0B, $1C, $C4
LNS_items_026:
	dc.b	$1D, $13, $16, $00, $1C, $13, $0C, $0C, $19, $18, $C4
LNS_items_027:
	dc.b	$1D, $13, $16, $00, $0D, $1C, $19, $21, $18, $C4
LNS_items_028:
	dc.b	$1E, $13, $1E, $0B, $18, $13, $11, $0F, $0B, $1C, $C4
LNS_items_029:
	dc.b	$1E, $13, $1E, $0B, $18, $13, $17, $0F, $1E, $C4
LNS_items_030:
	dc.b	$14, $21, $16, $00, $0D, $1C, $19, $21, $18, $C4
LNS_items_031:
	dc.b	$14, $21, $16, $00, $1C, $13, $0C, $0C, $19, $18, $C4
LNS_items_032:
	dc.b	$0D, $1C, $0F, $1D, $0D, $0F, $11, $0F, $0B, $1C, $C4
LNS_items_033:
	dc.b	$1D, $18, $19, $21, $00, $0D, $1C, $19, $21, $18, $C4
LNS_items_034:
	dc.b	$21, $13, $18, $0E, $00, $1D, $0D, $0B, $1C, $10, $C4
LNS_items_035:
	dc.b	$0D, $19, $16, $19, $1C, $1D, $0D, $0B, $1C, $10, $C4
LNS_items_036:
	dc.b	$1D, $1E, $19, $1C, $17, $00, $11, $0F, $0B, $1C, $C4
LNS_items_037:
	dc.b	$16, $0B, $0D, $19, $18, $13, $11, $0F, $0B, $1C, $C4
LNS_items_038:
	dc.b	$16, $0B, $0D, $19, $18, $13, $0B, $17, $0F, $1E, $C4
LNS_items_039:
	dc.b	$18, $0F, $13, $17, $0F, $1E, $C4
LNS_items_040:
	dc.b	$18, $0F, $13, $0D, $1C, $19, $21, $18, $C4
LNS_items_041:
	dc.b	$17, $0B, $11, $13, $0D, $00, $0D, $0B, $1A, $C4
LNS_items_042:
	dc.b	$17, $19, $11, $13, $0D, $00, $0D, $0B, $1A, $C4
LNS_items_043:
	dc.b	$0D, $0B, $1C, $0C, $19, $18, $1D, $1F, $13, $1E, $C4
LNS_items_044:
	dc.b	$0D, $0B, $1C, $0C, $19, $18, $20, $0F, $1D, $1E, $C4
LNS_items_045:
	dc.b	$10, $13, $0C, $0F, $1C, $0D, $19, $0B, $1E, $C4
LNS_items_046:
	dc.b	$10, $13, $0C, $0F, $1C, $0D, $0B, $1A, $0F, $C4
LNS_items_047:
	dc.b	$10, $13, $0C, $0F, $1C, $20, $0F, $1D, $1E, $C4
LNS_items_048:
	dc.b	$1E, $1E, $18, $17, $00, $0B, $1C, $17, $19, $1C, $C4
LNS_items_049:
	dc.b	$1E, $1E, $18, $17, $00, $0D, $0B, $1A, $0F, $C4
LNS_items_050:
	dc.b	$1E, $1E, $18, $17, $00, $0D, $12, $0F, $1D, $1E, $C4
LNS_items_051:
	dc.b	$0D, $1C, $17, $0D, $00, $0B, $1C, $17, $19, $1C, $C4
LNS_items_052:
	dc.b	$0D, $1C, $17, $0D, $00, $0D, $0B, $1A, $0F, $C4
LNS_items_053:
	dc.b	$0D, $1C, $17, $0D, $00, $0D, $12, $0F, $1D, $1E, $C4
LNS_items_054:
	dc.b	$0B, $17, $0C, $0F, $1C, $00, $1C, $19, $0C, $0F, $C4
LNS_items_055:
	dc.b	$0D, $1C, $23, $1D, $1E, $0B, $18, $13, $1D, $12, $C4
LNS_items_056:
	dc.b	$0D, $1C, $23, $1D, $1E, $0D, $0B, $1A, $0F, $C4
LNS_items_057:
	dc.b	$0D, $1C, $23, $1D, $1E, $0D, $12, $0F, $1D, $1E, $C4
LNS_items_058:
	dc.b	$16, $0B, $0D, $19, $18, $13, $18, $13, $1D, $12, $C4
LNS_items_059:
	dc.b	$16, $0B, $0D, $19, $18, $0D, $0B, $1A, $0F, $C4
LNS_items_060:
	dc.b	$16, $0B, $0D, $19, $18, $0D, $12, $0F, $1D, $1E, $C4
LNS_items_061:
	dc.b	$18, $0F, $13, $0B, $1C, $17, $19, $1C, $C4
LNS_items_062:
	dc.b	$18, $0F, $13, $0D, $0B, $1A, $0F, $C4
LNS_items_063:
	dc.b	$1D, $12, $19, $0F, $1D, $C4
LNS_items_064:
	dc.b	$1D, $0B, $18, $0E, $0B, $16, $1D, $C4
LNS_items_065:
	dc.b	$0C, $19, $19, $1E, $1D, $C4
LNS_items_066:
	dc.b	$15, $18, $13, $10, $0F, $0C, $19, $19, $1E, $1D, $C4
LNS_items_067:
	dc.b	$16, $19, $18, $11, $00, $0C, $19, $19, $1E, $1D, $C4
LNS_items_068:
	dc.b	$12, $13, $1C, $24, $0B, $0C, $19, $19, $1E, $1D, $C4
LNS_items_069:
	dc.b	$1D, $12, $1F, $18, $0F, $0C, $19, $19, $1E, $1D, $C4
LNS_items_070:
	dc.b	$11, $0B, $1C, $0E, $0B, $0C, $19, $19, $1E, $1D, $C4
LNS_items_071:
	dc.b	$0D, $1C, $0C, $18, $1D, $12, $13, $0F, $16, $0E, $C4
LNS_items_072:
	dc.b	$0D, $1C, $0C, $18, $00, $0F, $17, $0F, $16, $C4
LNS_items_073:
	dc.b	$10, $13, $0C, $1C, $1D, $12, $13, $16, $0E, $C4
LNS_items_074:
	dc.b	$10, $13, $0C, $0F, $1C, $00, $0F, $17, $0F, $16, $C4
LNS_items_075:
	dc.b	$17, $13, $1C, $00, $1D, $12, $13, $0F, $16, $0E, $C4
LNS_items_076:
	dc.b	$17, $13, $1C, $00, $0F, $17, $0F, $16, $C4
LNS_items_077:
	dc.b	$0D, $0F, $1C, $00, $1D, $12, $13, $0F, $16, $0E, $C4
LNS_items_078:
	dc.b	$0D, $0F, $1C, $00, $0F, $17, $0F, $16, $C4
LNS_items_079:
	dc.b	$0B, $0F, $11, $13, $1D, $C4
LNS_items_080:
	dc.b	$11, $1C, $00, $1D, $16, $0F, $0F, $20, $0F, $1D, $C4
LNS_items_081:
	dc.b	$1E, $1C, $1F, $1E, $12, $00, $1D, $16, $20, $1D, $C4
LNS_items_082:
	dc.b	$16, $0B, $0D, $19, $18, $00, $0F, $17, $0F, $16, $C4
LNS_items_083:
	dc.b	$16, $0B, $0D, $00, $1D, $12, $13, $0F, $16, $0E, $C4
LNS_items_084:
	dc.b	$18, $0F, $13, $1D, $12, $13, $0F, $16, $0E, $C4
LNS_items_085:
	dc.b	$18, $0F, $13, $0F, $17, $0F, $16, $C4
LNS_items_086:
	dc.b	$15, $18, $13, $10, $0F, $C4
LNS_items_087:
	dc.b	$0E, $0B, $11, $11, $0F, $1C, $C4
LNS_items_088:
	dc.b	$1D, $0D, $0B, $16, $1A, $0F, $16, $C4
LNS_items_089:
	dc.b	$1D, $1E, $0F, $0F, $16, $00, $0C, $0B, $1C, $C4
LNS_items_090:
	dc.b	$0C, $19, $19, $17, $0F, $1C, $0B, $18, $11, $C4
LNS_items_091:
	dc.b	$1D, $16, $0B, $1D, $12, $0F, $1C, $C4
LNS_items_092:
	dc.b	$1D, $21, $19, $1C, $0E, $C4
LNS_items_093:
	dc.b	$21, $12, $13, $1A, $C4
LNS_items_094:
	dc.b	$0D, $0F, $1C, $0B, $17, $00, $1D, $21, $1C, $0E, $C4
LNS_items_095:
	dc.b	$0D, $0F, $1C, $0B, $17, $00, $15, $18, $10, $0F, $C4
LNS_items_096:
	dc.b	$0D, $0F, $1C, $0B, $17, $00, $0C, $0B, $1C, $C4
LNS_items_097:
	dc.b	$16, $0B, $1D, $1C, $00, $1D, $16, $1D, $12, $1C, $C4
LNS_items_098:
	dc.b	$16, $0B, $1D, $1C, $00, $1D, $21, $1C, $0E, $C4
LNS_items_099:
	dc.b	$16, $0B, $1D, $1C, $00, $0C, $0B, $1C, $C4
LNS_items_100:
	dc.b	$16, $0B, $1D, $0F, $1C, $00, $15, $18, $10, $0F, $C4
LNS_items_101:
	dc.b	$1D, $21, $0E, $00, $19, $10, $00, $0B, $18, $11, $C4
LNS_items_102:
	dc.b	$10, $13, $1C, $0F, $00, $1D, $16, $1D, $12, $1C, $C4
LNS_items_103:
	dc.b	$10, $13, $1C, $0F, $00, $1D, $1E, $0B, $10, $10, $C4
LNS_items_104:
	dc.b	$16, $0B, $0D, $18, $00, $17, $0B, $0D, $0F, $C4
LNS_items_105:
	dc.b	$16, $0B, $0D, $00, $0E, $0B, $11, $11, $0F, $1C, $C4
LNS_items_106:
	dc.b	$0B, $0D, $00, $1D, $16, $0B, $1D, $12, $1C, $00, $C4
LNS_items_107:
	dc.b	$16, $0B, $0D, $00, $1D, $21, $19, $1C, $0E, $C4
LNS_items_108:
	dc.b	$18, $0F, $13, $1D, $21, $19, $1C, $0E, $C4
LNS_items_109:
	dc.b	$18, $0F, $13, $1D, $16, $0B, $1D, $12, $0F, $1C, $C4
LNS_items_110:
	dc.b	$0C, $19, $21, $00, $11, $1F, $18, $C4
LNS_items_111:
	dc.b	$1D, $19, $18, $13, $0D, $00, $11, $1F, $18, $C4
LNS_items_112:
	dc.b	$1D, $12, $19, $1E, $11, $1F, $18, $C4
LNS_items_113:
	dc.b	$1D, $13, $16, $0F, $18, $1E, $1D, $12, $19, $1E, $C4
LNS_items_114:
	dc.b	$1A, $19, $13, $1D, $19, $18, $1D, $12, $19, $1E, $C4
LNS_items_115:
	dc.b	$0B, $0D, $13, $0E, $1D, $12, $19, $1E, $C4
LNS_items_116:
	dc.b	$0D, $0B, $18, $18, $19, $18, $C4
LNS_items_117:
	dc.b	$20, $1F, $16, $0D, $0B, $18, $C4
LNS_items_118:
	dc.b	$16, $0B, $1D, $0F, $1C, $00, $1D, $12, $19, $1E, $C4
LNS_items_119:
	dc.b	$16, $1D, $1C, $00, $0D, $0B, $18, $18, $19, $18, $C4
LNS_items_120:
	dc.b	$1A, $16, $1D, $00, $0D, $0B, $18, $18, $19, $18, $C4
LNS_items_121:
	dc.b	$1A, $1F, $16, $1D, $0F, $00, $20, $16, $0D, $18, $C4
LNS_items_122:
	dc.b	$18, $0F, $13, $1D, $12, $19, $1E, $C4
LNS_items_123:
	dc.b	$1A, $1C, $1D, $18, $00, $0D, $16, $1E, $12, $1D, $C4
LNS_items_124:
	dc.b	$1E, $0F, $13, $17, $C4
LNS_items_125:
	dc.b	$20, $13, $1D, $13, $1A, $12, $19, $18, $0F, $C4
LNS_items_126:
	dc.b	$1E, $C4
LNS_items_127:
	dc.b	$12, $C4
LNS_techs_000:
	dc.b	$C4
LNS_techs_001:
	dc.b	$10, $19, $13, $C4
LNS_techs_002:
	dc.b	$11, $13, $10, $19, $13, $C4
LNS_techs_003:
	dc.b	$18, $0B, $10, $19, $13, $C4
LNS_techs_004:
	dc.b	$24, $0B, $18, $C4
LNS_techs_005:
	dc.b	$11, $13, $24, $0B, $18, $C4
LNS_techs_006:
	dc.b	$18, $0B, $24, $0B, $18, $C4
LNS_techs_007:
	dc.b	$11, $1C, $0B, $C4
LNS_techs_008:
	dc.b	$11, $13, $11, $1C, $0B, $C4
LNS_techs_009:
	dc.b	$18, $0B, $11, $1C, $0B, $C4
LNS_techs_010:
	dc.b	$1E, $1D, $1F, $C4
LNS_techs_011:
	dc.b	$11, $13, $1E, $12, $1F, $C4
LNS_techs_012:
	dc.b	$18, $0B, $1E, $12, $1F, $C4
LNS_techs_013:
	dc.b	$1D, $12, $13, $10, $1E, $C4
LNS_techs_014:
	dc.b	$10, $0B, $18, $0C, $13, $C4
LNS_techs_015:
	dc.b	$0F, $13, $14, $13, $0B, $C4
LNS_techs_016:
	dc.b	$0C, $1C, $19, $1D, $0F, $C4
LNS_techs_017:
	dc.b	$0D, $19, $18, $1E, $0F, $C4
LNS_techs_018:
	dc.b	$11, $0B, $14, $C4
LNS_techs_019:
	dc.b	$11, $13, $11, $0B, $14, $C4
LNS_techs_020:
	dc.b	$18, $0B, $11, $0B, $14, $C4
LNS_techs_021:
	dc.b	$1D, $0B, $11, $C4
LNS_techs_022:
	dc.b	$11, $13, $1D, $0B, $11, $C4
LNS_techs_023:
	dc.b	$18, $0B, $1D, $0B, $11, $C4
LNS_techs_024:
	dc.b	$11, $0F, $18, $C4
LNS_techs_025:
	dc.b	$1D, $0B, $11, $0F, $18, $C4
LNS_techs_026:
	dc.b	$20, $19, $16, $C4
LNS_techs_027:
	dc.b	$1D, $0B, $20, $19, $16, $C4
LNS_techs_028:
	dc.b	$1D, $12, $13, $24, $0B, $C4
LNS_techs_029:
	dc.b	$0E, $19, $1C, $0B, $18, $C4
LNS_techs_030:
	dc.b	$1C, $13, $17, $13, $1E, $C4
LNS_techs_031:
	dc.b	$1D, $12, $13, $18, $0C, $C4
LNS_techs_032:
	dc.b	$10, $19, $1C, $1D, $0B, $C4
LNS_techs_033:
	dc.b	$1C, $13, $17, $0F, $1E, $C4
LNS_techs_034:
	dc.b	$1D, $12, $1F, $C4
LNS_techs_035:
	dc.b	$1D, $0B, $1D, $12, $1F, $C4
LNS_techs_036:
	dc.b	$0E, $0F, $0C, $0B, $18, $C4
LNS_techs_037:
	dc.b	$18, $0F, $1C, $C4
LNS_techs_038:
	dc.b	$1D, $0B, $18, $0F, $1C, $C4
LNS_techs_039:
	dc.b	$1C, $0F, $1D, $C4
LNS_techs_040:
	dc.b	$11, $13, $1C, $0F, $1D, $C4
LNS_techs_041:
	dc.b	$18, $0B, $1C, $0F, $1D, $C4
LNS_techs_042:
	dc.b	$1D, $0B, $1C, $C4
LNS_techs_043:
	dc.b	$11, $13, $1D, $0B, $1C, $C4
LNS_techs_044:
	dc.b	$18, $0B, $1D, $0B, $1C, $C4
LNS_techs_045:
	dc.b	$1D, $0B, $15, $C4
LNS_techs_046:
	dc.b	$18, $0B, $1D, $0B, $15, $C4
LNS_techs_047:
	dc.b	$0B, $18, $1E, $13, $C4
LNS_techs_048:
	dc.b	$1C, $0F, $20, $0F, $1C, $C4
LNS_techs_049:
	dc.b	$1C, $23, $1F, $15, $0B, $C4
LNS_techs_050:
	dc.b	$12, $13, $18, $0B, $1D, $C4
LNS_techs_051:
	dc.b	$17, $1F, $1D, $13, $15, $C4
LNS_techs_052:
	dc.b	$17, $0F, $11, $13, $0E, $C4
LNS_techs_053:
	dc.b	$1C, $1C, $1C, $1C, $1C, $C4
LNS_techs_054:
	dc.b	$C4
LNS_techs_055:
	dc.b	$C4
LNS_techs_056:
	dc.b	$C4
LNS_techs_057:
	dc.b	$C4
LNS_techs_058:
	dc.b	$C4
LNS_techs_059:
	dc.b	$C4
LNS_techs_060:
	dc.b	$C4
LNS_techs_061:
	dc.b	$C4
LNS_techs_062:
	dc.b	$C4
LNS_techs_063:
	dc.b	$C4
LNS_enemies_000:
	dc.b	$C4
LNS_enemies_001:
	dc.b	$10, $13, $1C, $0F, $00, $0B, $18, $1E, $C4
LNS_enemies_002:
	dc.b	$0B, $1C, $17, $19, $1C, $0B, $18, $1E, $C4
LNS_enemies_003:
	dc.b	$1A, $13, $18, $0D, $12, $0B, $18, $1E, $C4
LNS_enemies_004:
	dc.b	$17, $19, $1D, $1B, $1F, $13, $1E, $19, $C4
LNS_enemies_005:
	dc.b	$21, $0B, $1D, $1A, $23, $C4
LNS_enemies_006:
	dc.b	$1D, $1E, $13, $18, $11, $0F, $1C, $C4
LNS_enemies_007:
	dc.b	$1D, $1A, $13, $18, $18, $0F, $1C, $C4
LNS_enemies_008:
	dc.b	$20, $19, $1C, $1E, $0F, $22, $C4
LNS_enemies_009:
	dc.b	$21, $12, $13, $1C, $16, $23, $C4
LNS_enemies_010:
	dc.b	$0C, $0F, $0F, $C4
LNS_enemies_011:
	dc.b	$0C, $1F, $24, $24, $0F, $1C, $C4
LNS_enemies_012:
	dc.b	$13, $18, $1D, $0F, $0D, $1E, $0B, $C4
LNS_enemies_013:
	dc.b	$1A, $19, $13, $1D, $19, $18, $0F, $1C, $C4
LNS_enemies_014:
	dc.b	$1D, $1A, $13, $1E, $15, $13, $16, $16, $C4
LNS_enemies_015:
	dc.b	$1D, $1A, $13, $1E, $10, $0B, $18, $11, $C4
LNS_enemies_016:
	dc.b	$12, $13, $1E, $00, $1E, $0B, $13, $16, $C4
LNS_enemies_017:
	dc.b	$0D, $0F, $18, $1E, $0F, $1C, $C4
LNS_enemies_018:
	dc.b	$1D, $0D, $0B, $16, $23, $C4
LNS_enemies_019:
	dc.b	$10, $1C, $19, $11, $11, $23, $C4
LNS_enemies_020:
	dc.b	$1E, $19, $0B, $0E, $0F, $1C, $C4
LNS_enemies_021:
	dc.b	$1D, $1B, $1F, $0B, $1E, $C4
LNS_enemies_022:
	dc.b	$0D, $0B, $1C, $1C, $13, $0F, $1C, $C4
LNS_enemies_023:
	dc.b	$17, $1F, $1D, $12, $1C, $19, $19, $17, $C4
LNS_enemies_024:
	dc.b	$12, $0F, $0B, $0E, $00, $1C, $19, $1E, $C4
LNS_enemies_025:
	dc.b	$21, $12, $13, $1D, $1E, $16, $0F, $C4
LNS_enemies_026:
	dc.b	$13, $18, $10, $19, $1C, $17, $0F, $1C, $C4
LNS_enemies_027:
	dc.b	$1E, $1C, $0B, $0D, $0F, $1C, $C4
LNS_enemies_028:
	dc.b	$16, $19, $0D, $1F, $1D, $1E, $C4
LNS_enemies_029:
	dc.b	$16, $19, $0D, $1F, $1D, $1E, $0B, $C4
LNS_enemies_030:
	dc.b	$10, $0B, $18, $0C, $13, $1E, $0F, $C4
LNS_enemies_031:
	dc.b	$0B, $17, $19, $0F, $0C, $0B, $C4
LNS_enemies_032:
	dc.b	$14, $0F, $16, $16, $23, $C4
LNS_enemies_033:
	dc.b	$1D, $16, $1F, $11, $17, $0F, $1D, $1D, $C4
LNS_enemies_034:
	dc.b	$1A, $19, $16, $0F, $24, $13, $C4
LNS_enemies_035:
	dc.b	$1A, $19, $16, $0F, $24, $13, $0B, $22, $C4
LNS_enemies_036:
	dc.b	$1A, $19, $16, $0F, $24, $13, $1D, $1D, $C4
LNS_enemies_037:
	dc.b	$16, $0F, $0F, $0D, $12, $0F, $1C, $C4
LNS_enemies_038:
	dc.b	$10, $0B, $18, $11, $C4
LNS_enemies_039:
	dc.b	$1A, $23, $1E, $12, $19, $18, $C4
LNS_enemies_040:
	dc.b	$1D, $C4
LNS_enemies_041:
	dc.b	$15, $C4
LNS_enemies_042:
	dc.b	$12, $C4
LNS_enemies_043:
	dc.b	$1A, $1F, $16, $1D, $0F, $1C, $C4
LNS_enemies_044:
	dc.b	$0C, $16, $0B, $1D, $1E, $0F, $1C, $C4
LNS_enemies_045:
	dc.b	$0C, $16, $0B, $1D, $1E, $19, $13, $0E, $C4
LNS_enemies_046:
	dc.b	$1C, $19, $1E, $00, $21, $19, $19, $0E, $C4
LNS_enemies_047:
	dc.b	$0C, $16, $19, $0D, $15, $12, $0F, $0E, $C4
LNS_enemies_048:
	dc.b	$10, $13, $1C, $13, $0B, $C4
LNS_enemies_049:
	dc.b	$21, $19, $16, $10, $0B, $18, $11, $C4
LNS_enemies_050:
	dc.b	$0C, $1F, $1C, $18, $21, $19, $16, $10, $C4
LNS_enemies_051:
	dc.b	$10, $16, $0B, $1C, $0F, $21, $16, $10, $C4
LNS_enemies_052:
	dc.b	$1A, $1F, $11, $00, $12, $13, $1E, $C4
LNS_enemies_053:
	dc.b	$1A, $1F, $11, $00, $0C, $1C, $0B, $1E, $C4
LNS_enemies_054:
	dc.b	$1A, $1F, $11, $00, $15, $13, $16, $16, $C4
LNS_enemies_055:
	dc.b	$1D, $C4
LNS_enemies_056:
	dc.b	$1D, $C4
LNS_enemies_057:
	dc.b	$1D, $C4
LNS_enemies_058:
	dc.b	$21, $13, $1C, $0F, $10, $0B, $0D, $0F, $C4
LNS_enemies_059:
	dc.b	$21, $13, $1C, $0F, $12, $0F, $0B, $0E, $C4
LNS_enemies_060:
	dc.b	$1A, $19, $0E, $00, $12, $0F, $0B, $0E, $C4
LNS_enemies_061:
	dc.b	$1E, $0F, $1C, $0B, $15, $13, $1E, $0F, $C4
LNS_enemies_062:
	dc.b	$1C, $0F, $1A, $1E, $13, $16, $0F, $C4
LNS_enemies_063:
	dc.b	$15, $13, $1E, $0F, $0E, $1C, $11, $18, $C4
LNS_enemies_064:
	dc.b	$10, $13, $1C, $0F, $46, $0F, $23, $0F, $C4
LNS_enemies_065:
	dc.b	$11, $16, $19, $21, $1D, $1E, $13, $15, $C4
LNS_enemies_066:
	dc.b	$10, $19, $1C, $0F, $1D, $1E, $C4
LNS_enemies_067:
	dc.b	$0D, $0B, $1E, $17, $0B, $18, $C4
LNS_enemies_068:
	dc.b	$0D, $0B, $1E, $10, $0B, $18, $11, $C4
LNS_enemies_069:
	dc.b	$0D, $0B, $1E, $0F, $23, $0F, $C4
LNS_enemies_070:
	dc.b	$17, $0F, $0D, $12, $19, $17, $0B, $18, $C4
LNS_enemies_071:
	dc.b	$1D, $19, $18, $19, $17, $0F, $0D, $12, $C4
LNS_enemies_072:
	dc.b	$0B, $1E, $1E, $17, $0F, $0D, $12, $C4
LNS_enemies_073:
	dc.b	$17, $0B, $24, $11, $0B, $17, $17, $0B, $C4
LNS_enemies_074:
	dc.b	$10, $13, $1C, $11, $0B, $17, $17, $0B, $C4
LNS_enemies_075:
	dc.b	$15, $13, $16, $11, $0B, $17, $17, $0B, $C4
LNS_enemies_076:
	dc.b	$17, $0F, $1E, $0B, $16, $17, $0B, $18, $C4
LNS_enemies_077:
	dc.b	$1E, $21, $13, $11, $00, $17, $0B, $18, $C4
LNS_enemies_078:
	dc.b	$1E, $21, $13, $11, $1E, $0B, $16, $16, $C4
LNS_enemies_079:
	dc.b	$0D, $19, $19, $16, $0F, $23, $07, $02, $C4
LNS_enemies_080:
	dc.b	$17, $19, $18, $1D, $1E, $0F, $1C, $C4
LNS_enemies_081:
	dc.b	$16, $1C, $11, $17, $13, $18, $0F, $1C, $C4
LNS_enemies_082:
	dc.b	$0F, $23, $0F, $1D, $19, $1C, $0F, $C4
LNS_enemies_083:
	dc.b	$12, $20, $23, $1D, $19, $16, $13, $0E, $C4
LNS_enemies_084:
	dc.b	$11, $1F, $18, $00, $0C, $1F, $1D, $1E, $C4
LNS_enemies_085:
	dc.b	$0B, $1C, $17, $23, $00, $0F, $23, $0F, $C4
LNS_enemies_086:
	dc.b	$1E, $1C, $0D, $1C, $0C, $0B, $1D, $0F, $C4
LNS_enemies_087:
	dc.b	$1D, $1A, $0F, $0D, $1E, $0F, $1C, $C4
LNS_enemies_088:
	dc.b	$20, $0B, $18, $C4
LNS_enemies_089:
	dc.b	$20, $0B, $18, $16, $0F, $0B, $0E, $1C, $C4
LNS_enemies_090:
	dc.b	$0B, $0F, $1C, $19, $1E, $0B, $18, $15, $C4
LNS_enemies_091:
	dc.b	$19, $1C, $0B, $18, $11, $0B, $12, $C4
LNS_enemies_092:
	dc.b	$19, $1C, $0B, $18, $11, $19, $19, $C4
LNS_enemies_093:
	dc.b	$19, $12, $22, $C4
LNS_enemies_094:
	dc.b	$17, $0B, $1D, $1E, $19, $0E, $19, $18, $C4
LNS_enemies_095:
	dc.b	$0F, $16, $0F, $1E, $1F, $1D, $15, $C4
LNS_enemies_096:
	dc.b	$0F, $16, $0F, $1A, $12, $0B, $18, $1E, $C4
LNS_enemies_097:
	dc.b	$0E, $0F, $24, $19, $00, $19, $21, $16, $C4
LNS_enemies_098:
	dc.b	$1D, $15, $23, $1E, $13, $0B, $1C, $0B, $C4
LNS_enemies_099:
	dc.b	$19, $21, $16, $1E, $0B, $16, $19, $18, $C4
LNS_enemies_100:
	dc.b	$1C, $0B, $0C, $0C, $13, $1E, $C4
LNS_enemies_101:
	dc.b	$1C, $0B, $0C, $13, $1E, $1E, $0B, $C4
LNS_enemies_102:
	dc.b	$1C, $0B, $0C, $13, $1E, $11, $1F, $1E, $C4
LNS_enemies_103:
	dc.b	$21, $1C, $0F, $1D, $1E, $16, $0F, $1C, $C4
LNS_enemies_104:
	dc.b	$1D, $0B, $15, $19, $10, $10, $C4
LNS_enemies_105:
	dc.b	$17, $0F, $1D, $19, $17, $0B, $18, $C4
LNS_enemies_106:
	dc.b	$16, $1F, $18, $11, $C4
LNS_enemies_107:
	dc.b	$11, $16, $19, $1D, $21, $19, $1C, $0E, $C4
LNS_enemies_108:
	dc.b	$0E, $0F, $1D, $1C, $19, $18, $0B, $C4
LNS_enemies_109:
	dc.b	$0E, $0B, $1C, $15, $1D, $13, $0E, $0F, $C4
LNS_enemies_110:
	dc.b	$17, $1C, $00, $0E, $0F, $0B, $1E, $12, $C4
LNS_enemies_111:
	dc.b	$1D, $12, $0B, $0E, $19, $21, $C4
LNS_enemies_112:
	dc.b	$17, $23, $1D, $1E, $0D, $0B, $1A, $0F, $C4
LNS_enemies_113:
	dc.b	$13, $16, $16, $1F, $1D, $18, $1D, $1E, $C4
LNS_enemies_114:
	dc.b	$13, $17, $0B, $11, $13, $19, $17, $11, $C4
LNS_enemies_115:
	dc.b	$0B, $1C, $0D, $12, $0E, $1C, $11, $18, $C4
LNS_enemies_116:
	dc.b	$10, $1C, $0E, $1C, $0B, $11, $19, $18, $C4
LNS_enemies_117:
	dc.b	$17, $22, $0E, $1C, $0B, $11, $19, $18, $C4
LNS_enemies_118:
	dc.b	$10, $13, $1C, $0F, $10, $0B, $16, $16, $C4
LNS_enemies_119:
	dc.b	$20, $19, $1C, $0D, $0B, $18, $19, $C4
LNS_enemies_120:
	dc.b	$15, $13, $18, $11, $16, $0B, $20, $0B, $C4
LNS_enemies_121:
	dc.b	$21, $13, $24, $0B, $1C, $0E, $C4
LNS_enemies_122:
	dc.b	$0D, $0B, $1A, $0F, $19, $18, $0F, $C4
LNS_enemies_123:
	dc.b	$10, $13, $0F, $18, $0E, $C4
LNS_enemies_124:
	dc.b	$18, $0F, $13, $10, $13, $1C, $1D, $1E, $C4
LNS_enemies_125:
	dc.b	$0E, $0B, $1C, $15, $10, $1C, $0D, $0F, $C4
LNS_enemies_126:
	dc.b	$17, $19, $17, $0C, $1C, $0B, $13, $18, $C4
	even
