; Generated by tools/gentext.py from work/script.json (items, techs, enemies, teleport, soundtracks, jobs):
; the full-length names, a pointer per record (ext/longnames.asm). Do not edit.
LN_Ranges:
	dc.l	InventoryData, InventoryData+2048, LN_Items
	dc.w	16, 0
	dc.l	TechniqueData, TechniqueData+512, LN_Techs
	dc.w	8, 0
	dc.l	EnemyNames, EnemyNames+1270, LN_Enemies
	dc.w	10, 0
	dc.l	TeleportPlaceNamesArray, TeleportPlaceNamesArray+50, LN_Places
	dc.w	5, 0
	dc.l	SoundtrackCharArray, SoundtrackCharArray+264, LN_Tracks
	dc.w	12, 0
	dc.l	loc_11456, loc_11456+64, LN_Jobs
	dc.w	8, 0
	dc.l	0
LN_Items_N = 128
LN_Items:
	dc.l	LNS_items_000, LNS_items_001, LNS_items_002, LNS_items_003, LNS_items_004, LNS_items_005, LNS_items_006, LNS_items_007
	dc.l	LNS_items_008, LNS_items_009, LNS_items_010, LNS_items_011, LNS_items_012, LNS_items_013, LNS_items_014, LNS_items_015
	dc.l	LNS_items_016, LNS_items_017, LNS_items_018, LNS_items_019, LNS_items_020, LNS_items_021, LNS_items_022, LNS_items_023
	dc.l	LNS_items_024, LNS_items_025, LNS_items_026, LNS_items_027, LNS_items_028, LNS_items_029, LNS_items_030, LNS_items_031
	dc.l	LNS_items_032, LNS_items_033, LNS_items_034, LNS_items_035, LNS_items_036, LNS_items_037, LNS_items_038, LNS_items_039
	dc.l	LNS_items_040, LNS_items_041, LNS_items_042, LNS_items_043, LNS_items_044, LNS_items_045, LNS_items_046, LNS_items_047
	dc.l	LNS_items_048, LNS_items_049, LNS_items_050, LNS_items_051, LNS_items_052, LNS_items_053, LNS_items_054, LNS_items_055
	dc.l	LNS_items_056, LNS_items_057, LNS_items_058, LNS_items_059, LNS_items_060, LNS_items_061, LNS_items_062, LNS_items_063
	dc.l	LNS_items_064, LNS_items_065, LNS_items_066, LNS_items_067, LNS_items_068, LNS_items_069, LNS_items_070, LNS_items_071
	dc.l	LNS_items_072, LNS_items_073, LNS_items_074, LNS_items_075, LNS_items_076, LNS_items_077, LNS_items_078, LNS_items_079
	dc.l	LNS_items_080, LNS_items_081, LNS_items_082, LNS_items_083, LNS_items_084, LNS_items_085, LNS_items_086, LNS_items_087
	dc.l	LNS_items_088, LNS_items_089, LNS_items_090, LNS_items_091, LNS_items_092, LNS_items_093, LNS_items_094, LNS_items_095
	dc.l	LNS_items_096, LNS_items_097, LNS_items_098, LNS_items_099, LNS_items_100, LNS_items_101, LNS_items_102, LNS_items_103
	dc.l	LNS_items_104, LNS_items_105, LNS_items_106, LNS_items_107, LNS_items_108, LNS_items_109, LNS_items_110, LNS_items_111
	dc.l	LNS_items_112, LNS_items_113, LNS_items_114, LNS_items_115, LNS_items_116, LNS_items_117, LNS_items_118, LNS_items_119
	dc.l	LNS_items_120, LNS_items_121, LNS_items_122, LNS_items_123, LNS_items_124, LNS_items_125, LNS_items_126, LNS_items_127
LN_Techs_N = 64
LN_Techs:
	dc.l	LNS_techs_000, LNS_techs_001, LNS_techs_002, LNS_techs_003, LNS_techs_004, LNS_techs_005, LNS_techs_006, LNS_techs_007
	dc.l	LNS_techs_008, LNS_techs_009, LNS_techs_010, LNS_techs_011, LNS_techs_012, LNS_techs_013, LNS_techs_014, LNS_techs_015
	dc.l	LNS_techs_016, LNS_techs_017, LNS_techs_018, LNS_techs_019, LNS_techs_020, LNS_techs_021, LNS_techs_022, LNS_techs_023
	dc.l	LNS_techs_024, LNS_techs_025, LNS_techs_026, LNS_techs_027, LNS_techs_028, LNS_techs_029, LNS_techs_030, LNS_techs_031
	dc.l	LNS_techs_032, LNS_techs_033, LNS_techs_034, LNS_techs_035, LNS_techs_036, LNS_techs_037, LNS_techs_038, LNS_techs_039
	dc.l	LNS_techs_040, LNS_techs_041, LNS_techs_042, LNS_techs_043, LNS_techs_044, LNS_techs_045, LNS_techs_046, LNS_techs_047
	dc.l	LNS_techs_048, LNS_techs_049, LNS_techs_050, LNS_techs_051, LNS_techs_052, LNS_techs_053, LNS_techs_054, LNS_techs_055
	dc.l	LNS_techs_056, LNS_techs_057, LNS_techs_058, LNS_techs_059, LNS_techs_060, LNS_techs_061, LNS_techs_062, LNS_techs_063
LN_Enemies_N = 127
LN_Enemies:
	dc.l	LNS_enemies_000, LNS_enemies_001, LNS_enemies_002, LNS_enemies_003, LNS_enemies_004, LNS_enemies_005, LNS_enemies_006, LNS_enemies_007
	dc.l	LNS_enemies_008, LNS_enemies_009, LNS_enemies_010, LNS_enemies_011, LNS_enemies_012, LNS_enemies_013, LNS_enemies_014, LNS_enemies_015
	dc.l	LNS_enemies_016, LNS_enemies_017, LNS_enemies_018, LNS_enemies_019, LNS_enemies_020, LNS_enemies_021, LNS_enemies_022, LNS_enemies_023
	dc.l	LNS_enemies_024, LNS_enemies_025, LNS_enemies_026, LNS_enemies_027, LNS_enemies_028, LNS_enemies_029, LNS_enemies_030, LNS_enemies_031
	dc.l	LNS_enemies_032, LNS_enemies_033, LNS_enemies_034, LNS_enemies_035, LNS_enemies_036, LNS_enemies_037, LNS_enemies_038, LNS_enemies_039
	dc.l	LNS_enemies_040, LNS_enemies_041, LNS_enemies_042, LNS_enemies_043, LNS_enemies_044, LNS_enemies_045, LNS_enemies_046, LNS_enemies_047
	dc.l	LNS_enemies_048, LNS_enemies_049, LNS_enemies_050, LNS_enemies_051, LNS_enemies_052, LNS_enemies_053, LNS_enemies_054, LNS_enemies_055
	dc.l	LNS_enemies_056, LNS_enemies_057, LNS_enemies_058, LNS_enemies_059, LNS_enemies_060, LNS_enemies_061, LNS_enemies_062, LNS_enemies_063
	dc.l	LNS_enemies_064, LNS_enemies_065, LNS_enemies_066, LNS_enemies_067, LNS_enemies_068, LNS_enemies_069, LNS_enemies_070, LNS_enemies_071
	dc.l	LNS_enemies_072, LNS_enemies_073, LNS_enemies_074, LNS_enemies_075, LNS_enemies_076, LNS_enemies_077, LNS_enemies_078, LNS_enemies_079
	dc.l	LNS_enemies_080, LNS_enemies_081, LNS_enemies_082, LNS_enemies_083, LNS_enemies_084, LNS_enemies_085, LNS_enemies_086, LNS_enemies_087
	dc.l	LNS_enemies_088, LNS_enemies_089, LNS_enemies_090, LNS_enemies_091, LNS_enemies_092, LNS_enemies_093, LNS_enemies_094, LNS_enemies_095
	dc.l	LNS_enemies_096, LNS_enemies_097, LNS_enemies_098, LNS_enemies_099, LNS_enemies_100, LNS_enemies_101, LNS_enemies_102, LNS_enemies_103
	dc.l	LNS_enemies_104, LNS_enemies_105, LNS_enemies_106, LNS_enemies_107, LNS_enemies_108, LNS_enemies_109, LNS_enemies_110, LNS_enemies_111
	dc.l	LNS_enemies_112, LNS_enemies_113, LNS_enemies_114, LNS_enemies_115, LNS_enemies_116, LNS_enemies_117, LNS_enemies_118, LNS_enemies_119
	dc.l	LNS_enemies_120, LNS_enemies_121, LNS_enemies_122, LNS_enemies_123, LNS_enemies_124, LNS_enemies_125, LNS_enemies_126
LN_Places_N = 10
LN_Places:
	dc.l	LNS_teleport_000, LNS_teleport_001, LNS_teleport_002, LNS_teleport_003, LNS_teleport_004, LNS_teleport_005, LNS_teleport_006, LNS_teleport_007
	dc.l	LNS_teleport_008, LNS_teleport_009
LN_Tracks_N = 22
LN_Tracks:
	dc.l	LNS_soundtracks_000, LNS_soundtracks_001, LNS_soundtracks_002, LNS_soundtracks_003, LNS_soundtracks_004, LNS_soundtracks_005, LNS_soundtracks_006, LNS_soundtracks_007
	dc.l	LNS_soundtracks_008, LNS_soundtracks_009, LNS_soundtracks_010, LNS_soundtracks_011, LNS_soundtracks_012, LNS_soundtracks_013, LNS_soundtracks_014, LNS_soundtracks_015
	dc.l	LNS_soundtracks_016, LNS_soundtracks_017, LNS_soundtracks_018, LNS_soundtracks_019, LNS_soundtracks_020, LNS_soundtracks_021
LN_Jobs_N = 8
LN_Jobs:
	dc.l	LNS_jobs_000, LNS_jobs_001, LNS_jobs_002, LNS_jobs_003, LNS_jobs_004, LNS_jobs_005, LNS_jobs_006, LNS_jobs_007
LNS_items_000:
	dc.b	$C4
LNS_items_001:
	dc.b	$1D, $31, $25, $30, $30, $00, $15, $29, $3D, $C4
LNS_items_002:
	dc.b	$0E, $3D, $32, $25, $31, $2D, $38, $29, $C4
LNS_items_003:
	dc.b	$15, $29, $3D, $00, $1E, $39, $26, $29, $C4
LNS_items_004:
	dc.b	$17, $25, $36, $39, $29, $36, $25, $00, $11, $39, $31, $C4
LNS_items_005:
	dc.b	$11, $36, $29, $29, $32, $00, $0D, $25, $36, $28, $C4
LNS_items_006:
	dc.b	$0C, $30, $39, $29, $00, $0D, $25, $36, $28, $C4
LNS_items_007:
	dc.b	$23, $29, $30, $30, $33, $3B, $00, $0D, $25, $36, $28, $C4
LNS_items_008:
	dc.b	$1C, $29, $28, $00, $0D, $25, $36, $28, $C4
LNS_items_009:
	dc.b	$1E, $2C, $36, $29, $25, $38, $29, $32, $2D, $32, $2B, $00, $16, $29, $38, $38
	dc.b	$29, $36, $C4
LNS_items_010:
	dc.b	$1D, $3D, $37, $38, $29, $31, $00, $1C, $29, $27, $33, $36, $28, $29, $36, $C4
LNS_items_011:
	dc.b	$17, $25, $36, $39, $29, $36, $25, $00, $16, $29, $25, $2A, $C4
LNS_items_012:
	dc.b	$1A, $30, $25, $37, $31, $25, $00, $1C, $2D, $32, $2B, $C4
LNS_items_013:
	dc.b	$0B, $29, $36, $33, $34, $36, $2D, $37, $31, $C4
LNS_items_014:
	dc.b	$1E, $36, $25, $3A, $29, $30, $00, $19, $27, $25, $36, $2D, $32, $25, $C4
LNS_items_015:
	dc.b	$16, $33, $37, $38, $00, $19, $27, $25, $36, $2D, $32, $25, $C4
LNS_items_016:
	dc.b	$1D, $2C, $2D, $32, $33, $26, $2D, $45, $37, $00, $19, $27, $25, $36, $2D, $32
	dc.b	$25, $C4
LNS_items_017:
	dc.b	$17, $33, $32, $33, $31, $25, $38, $29, $C4
LNS_items_018:
	dc.b	$0E, $2D, $31, $25, $38, $29, $C4
LNS_items_019:
	dc.b	$1E, $36, $2D, $31, $25, $38, $29, $C4
LNS_items_020:
	dc.b	$0B, $32, $38, $2D, $34, $33, $2D, $37, $33, $32, $C4
LNS_items_021:
	dc.b	$1D, $38, $25, $36, $00, $0B, $38, $33, $31, $2D, $3E, $29, $36, $C4
LNS_items_022:
	dc.b	$17, $33, $33, $32, $00, $0B, $38, $33, $31, $2D, $3E, $29, $36, $C4
LNS_items_023:
	dc.b	$12, $29, $25, $28, $2B, $29, $25, $36, $C4
LNS_items_024:
	dc.b	$1C, $2D, $26, $26, $33, $32, $C4
LNS_items_025:
	dc.b	$11, $30, $25, $37, $37, $00, $11, $29, $25, $36, $C4
LNS_items_026:
	dc.b	$1D, $2D, $30, $3A, $29, $36, $00, $1C, $2D, $26, $26, $33, $32, $C4
LNS_items_027:
	dc.b	$1D, $2D, $30, $3A, $29, $36, $00, $0D, $36, $33, $3B, $32, $C4
LNS_items_028:
	dc.b	$1E, $2D, $38, $25, $32, $2D, $39, $31, $00, $11, $29, $25, $36, $C4
LNS_items_029:
	dc.b	$1E, $2D, $38, $25, $32, $2D, $39, $31, $00, $12, $29, $30, $31, $C4
LNS_items_030:
	dc.b	$14, $29, $3B, $29, $30, $00, $0D, $36, $33, $3B, $32, $C4
LNS_items_031:
	dc.b	$14, $29, $3B, $29, $30, $00, $1C, $2D, $26, $26, $33, $32, $C4
LNS_items_032:
	dc.b	$0D, $36, $29, $37, $27, $29, $32, $38, $00, $11, $29, $25, $36, $C4
LNS_items_033:
	dc.b	$1D, $32, $33, $3B, $00, $0D, $36, $33, $3B, $32, $C4
LNS_items_034:
	dc.b	$21, $2D, $32, $28, $00, $0C, $25, $32, $28, $25, $32, $25, $C4
LNS_items_035:
	dc.b	$1C, $25, $2D, $32, $26, $33, $3B, $00, $0C, $25, $32, $28, $25, $32, $25, $C4
LNS_items_036:
	dc.b	$1D, $38, $33, $36, $31, $00, $11, $29, $25, $36, $C4
LNS_items_037:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $11, $29, $25, $36, $C4
LNS_items_038:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $12, $29, $30, $31, $C4
LNS_items_039:
	dc.b	$18, $29, $2D, $00, $12, $29, $30, $31, $C4
LNS_items_040:
	dc.b	$18, $29, $2D, $00, $0D, $36, $33, $3B, $32, $C4
LNS_items_041:
	dc.b	$17, $25, $2B, $2D, $27, $00, $12, $25, $38, $C4
LNS_items_042:
	dc.b	$17, $33, $2B, $2D, $27, $00, $12, $25, $38, $C4
LNS_items_043:
	dc.b	$0D, $25, $36, $26, $33, $32, $00, $1D, $39, $2D, $38, $C4
LNS_items_044:
	dc.b	$0D, $25, $36, $26, $33, $32, $00, $20, $29, $37, $38, $C4
LNS_items_045:
	dc.b	$11, $30, $25, $37, $37, $00, $0D, $33, $25, $38, $C4
LNS_items_046:
	dc.b	$11, $30, $25, $37, $37, $00, $0D, $25, $34, $29, $C4
LNS_items_047:
	dc.b	$11, $30, $25, $37, $37, $00, $20, $29, $37, $38, $C4
LNS_items_048:
	dc.b	$1E, $2D, $38, $25, $32, $2D, $39, $31, $00, $0B, $36, $31, $33, $36, $C4
LNS_items_049:
	dc.b	$1E, $2D, $38, $25, $32, $2D, $39, $31, $00, $10, $2D, $26, $36, $2D, $30, $30
	dc.b	$25, $C4
LNS_items_050:
	dc.b	$1E, $2D, $38, $25, $32, $2D, $39, $31, $00, $0D, $2C, $29, $37, $38, $C4
LNS_items_051:
	dc.b	$0D, $29, $36, $25, $31, $2D, $27, $00, $0B, $36, $31, $33, $36, $C4
LNS_items_052:
	dc.b	$0D, $29, $36, $25, $31, $2D, $27, $00, $10, $2D, $26, $36, $2D, $30, $30, $25
	dc.b	$C4
LNS_items_053:
	dc.b	$0D, $29, $36, $25, $31, $2D, $27, $00, $0D, $2C, $29, $37, $38, $C4
LNS_items_054:
	dc.b	$0B, $31, $26, $29, $36, $00, $1C, $33, $26, $29, $C4
LNS_items_055:
	dc.b	$0D, $36, $3D, $37, $38, $25, $00, $12, $25, $36, $32, $2D, $37, $27, $2C, $C4
LNS_items_056:
	dc.b	$0D, $36, $3D, $37, $38, $25, $00, $10, $2D, $29, $30, $28, $C4
LNS_items_057:
	dc.b	$0D, $36, $3D, $37, $38, $25, $00, $0D, $2C, $29, $37, $38, $C4
LNS_items_058:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $12, $25, $36, $32, $2D, $37, $27, $2C
	dc.b	$C4
LNS_items_059:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $10, $2D, $26, $36, $2D, $30, $30, $25
	dc.b	$C4
LNS_items_060:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $0D, $2C, $29, $37, $38, $C4
LNS_items_061:
	dc.b	$18, $29, $2D, $00, $12, $25, $36, $32, $2D, $37, $27, $2C, $C4
LNS_items_062:
	dc.b	$18, $29, $2D, $00, $10, $2D, $29, $30, $28, $C4
LNS_items_063:
	dc.b	$16, $29, $25, $38, $2C, $29, $36, $00, $1D, $2C, $33, $29, $37, $C4
LNS_items_064:
	dc.b	$0F, $37, $34, $25, $28, $36, $2D, $30, $30, $29, $37, $C4
LNS_items_065:
	dc.b	$16, $29, $25, $38, $2C, $29, $36, $00, $0C, $33, $33, $38, $37, $C4
LNS_items_066:
	dc.b	$15, $32, $2D, $2A, $29, $00, $0C, $33, $33, $38, $37, $C4
LNS_items_067:
	dc.b	$16, $33, $32, $2B, $00, $0C, $33, $33, $38, $37, $C4
LNS_items_068:
	dc.b	$12, $29, $2D, $30, $37, $25, $31, $00, $0C, $33, $33, $38, $37, $C4
LNS_items_069:
	dc.b	$1D, $27, $2C, $32, $29, $30, $30, $25, $00, $0C, $33, $33, $38, $37, $C4
LNS_items_070:
	dc.b	$11, $39, $25, $36, $28, $25, $00, $0C, $33, $33, $38, $37, $C4
LNS_items_071:
	dc.b	$0D, $25, $36, $26, $33, $32, $00, $1D, $2C, $2D, $29, $30, $28, $C4
LNS_items_072:
	dc.b	$0D, $25, $36, $26, $33, $32, $00, $48, $36, $31, $29, $30, $C4
LNS_items_073:
	dc.b	$11, $30, $25, $37, $37, $00, $1D, $2C, $2D, $29, $30, $28, $C4
LNS_items_074:
	dc.b	$11, $30, $25, $37, $37, $00, $48, $36, $31, $29, $30, $C4
LNS_items_075:
	dc.b	$17, $2D, $36, $36, $33, $36, $00, $1D, $2C, $2D, $29, $30, $28, $C4
LNS_items_076:
	dc.b	$17, $2D, $36, $36, $33, $36, $00, $48, $36, $31, $29, $30, $C4
LNS_items_077:
	dc.b	$0D, $29, $36, $25, $31, $2D, $27, $00, $1D, $2C, $2D, $29, $30, $28, $C4
LNS_items_078:
	dc.b	$0D, $29, $36, $25, $31, $2D, $27, $00, $48, $36, $31, $29, $30, $C4
LNS_items_079:
	dc.b	$1D, $29, $36, $29, $32, $2D, $38, $3D, $00, $1D, $2C, $2D, $29, $30, $28, $C4
LNS_items_080:
	dc.b	$11, $36, $29, $29, $32, $00, $1D, $30, $29, $29, $3A, $29, $37, $C4
LNS_items_081:
	dc.b	$1D, $2D, $32, $27, $29, $36, $2D, $38, $3D, $00, $1D, $30, $29, $29, $3A, $29
	dc.b	$37, $C4
LNS_items_082:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $48, $36, $31, $29, $30, $C4
LNS_items_083:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $1D, $2C, $2D, $29, $30, $28, $C4
LNS_items_084:
	dc.b	$18, $29, $2D, $00, $1D, $2C, $2D, $29, $30, $28, $C4
LNS_items_085:
	dc.b	$18, $29, $2D, $00, $48, $36, $31, $29, $30, $C4
LNS_items_086:
	dc.b	$15, $32, $2D, $2A, $29, $C4
LNS_items_087:
	dc.b	$0E, $25, $2B, $2B, $29, $36, $C4
LNS_items_088:
	dc.b	$1D, $27, $25, $30, $34, $29, $30, $C4
LNS_items_089:
	dc.b	$1D, $38, $29, $29, $30, $00, $0D, $30, $25, $3B, $C4
LNS_items_090:
	dc.b	$0C, $33, $33, $31, $29, $36, $25, $32, $2B, $C4
LNS_items_091:
	dc.b	$1D, $30, $2D, $27, $29, $36, $C4
LNS_items_092:
	dc.b	$1D, $3B, $33, $36, $28, $C4
LNS_items_093:
	dc.b	$21, $2C, $2D, $34, $C4
LNS_items_094:
	dc.b	$0D, $29, $36, $25, $31, $2D, $27, $00, $1D, $3B, $33, $36, $28, $C4
LNS_items_095:
	dc.b	$0D, $29, $36, $25, $31, $2D, $27, $00, $15, $32, $2D, $2A, $29, $C4
LNS_items_096:
	dc.b	$0D, $29, $36, $25, $31, $2D, $27, $00, $0D, $30, $25, $3B, $C4
LNS_items_097:
	dc.b	$16, $25, $37, $29, $36, $00, $1D, $30, $2D, $27, $29, $36, $C4
LNS_items_098:
	dc.b	$16, $25, $37, $29, $36, $00, $1D, $3B, $33, $36, $28, $C4
LNS_items_099:
	dc.b	$16, $25, $37, $29, $36, $00, $0D, $30, $25, $3B, $C4
LNS_items_100:
	dc.b	$16, $25, $37, $29, $36, $00, $15, $32, $2D, $2A, $29, $C4
LNS_items_101:
	dc.b	$1D, $3B, $33, $36, $28, $00, $33, $2A, $00, $0B, $32, $2B, $29, $36, $C4
LNS_items_102:
	dc.b	$10, $2D, $36, $29, $00, $1D, $30, $2D, $27, $29, $36, $C4
LNS_items_103:
	dc.b	$10, $30, $25, $31, $29, $00, $1D, $38, $25, $2A, $2A, $C4
LNS_items_104:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $1D, $27, $25, $30, $29, $C4
LNS_items_105:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $0E, $25, $2B, $2B, $29, $36, $C4
LNS_items_106:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $1D, $30, $2D, $27, $29, $36, $C4
LNS_items_107:
	dc.b	$16, $25, $27, $33, $32, $2D, $25, $00, $1D, $3B, $33, $36, $28, $C4
LNS_items_108:
	dc.b	$18, $29, $2D, $00, $1D, $3B, $33, $36, $28, $C4
LNS_items_109:
	dc.b	$18, $29, $2D, $00, $1D, $30, $2D, $27, $29, $36, $C4
LNS_items_110:
	dc.b	$0C, $33, $3B, $2B, $39, $32, $C4
LNS_items_111:
	dc.b	$1D, $33, $32, $2D, $27, $00, $11, $39, $32, $C4
LNS_items_112:
	dc.b	$1D, $2C, $33, $38, $2B, $39, $32, $C4
LNS_items_113:
	dc.b	$1D, $2D, $30, $29, $32, $38, $00, $1D, $2C, $33, $38, $C4
LNS_items_114:
	dc.b	$1A, $33, $2D, $37, $33, $32, $00, $1D, $2C, $33, $38, $C4
LNS_items_115:
	dc.b	$0B, $27, $2D, $28, $00, $1D, $2C, $33, $38, $C4
LNS_items_116:
	dc.b	$0D, $25, $32, $32, $33, $32, $C4
LNS_items_117:
	dc.b	$20, $39, $30, $27, $25, $32, $C4
LNS_items_118:
	dc.b	$16, $25, $37, $29, $36, $00, $1D, $2C, $33, $38, $C4
LNS_items_119:
	dc.b	$16, $25, $37, $29, $36, $00, $0D, $25, $32, $32, $33, $32, $C4
LNS_items_120:
	dc.b	$1A, $39, $30, $37, $29, $00, $0D, $25, $32, $32, $33, $32, $C4
LNS_items_121:
	dc.b	$1A, $39, $30, $37, $29, $00, $20, $39, $30, $27, $25, $32, $C4
LNS_items_122:
	dc.b	$18, $29, $2D, $00, $1D, $2C, $33, $38, $C4
LNS_items_123:
	dc.b	$1A, $36, $2D, $37, $33, $32, $29, $36, $00, $0D, $30, $33, $38, $2C, $29, $37
	dc.b	$C4
LNS_items_124:
	dc.b	$1E, $2D, $29, $31, $C4
LNS_items_125:
	dc.b	$20, $2D, $37, $2D, $34, $2C, $33, $32, $29, $C4
LNS_items_126:
	dc.b	$1D, $38, $25, $38, $39, $29, $00, $33, $2A, $00, $1E, $3D, $36, $33, $32, $C4
LNS_items_127:
	dc.b	$12, $25, $34, $37, $26, $3D, $C4
LNS_techs_000:
	dc.b	$C4
LNS_techs_001:
	dc.b	$10, $33, $2D, $29, $C4
LNS_techs_002:
	dc.b	$11, $2D, $2A, $33, $2D, $29, $C4
LNS_techs_003:
	dc.b	$18, $25, $2A, $33, $2D, $29, $C4
LNS_techs_004:
	dc.b	$24, $25, $32, $C4
LNS_techs_005:
	dc.b	$11, $2D, $3E, $25, $32, $C4
LNS_techs_006:
	dc.b	$18, $25, $3E, $25, $32, $C4
LNS_techs_007:
	dc.b	$11, $36, $25, $3A, $38, $C4
LNS_techs_008:
	dc.b	$11, $2D, $2B, $36, $25, $3A, $38, $C4
LNS_techs_009:
	dc.b	$18, $25, $2B, $36, $25, $3A, $38, $C4
LNS_techs_010:
	dc.b	$11, $36, $25, $32, $38, $37, $C4
LNS_techs_011:
	dc.b	$11, $2D, $2B, $36, $25, $32, $38, $37, $C4
LNS_techs_012:
	dc.b	$18, $25, $2B, $36, $25, $32, $38, $37, $C4
LNS_techs_013:
	dc.b	$1D, $2C, $2D, $2A, $38, $25, $C4
LNS_techs_014:
	dc.b	$10, $25, $32, $26, $2D, $25, $C4
LNS_techs_015:
	dc.b	$0F, $2D, $2E, $2D, $25, $C4
LNS_techs_016:
	dc.b	$1A, $36, $33, $27, $29, $28, $25, $32, $C4
LNS_techs_017:
	dc.b	$15, $33, $32, $38, $29, $36, $C4
LNS_techs_018:
	dc.b	$11, $25, $2E, $C4
LNS_techs_019:
	dc.b	$11, $2D, $2B, $25, $2E, $C4
LNS_techs_020:
	dc.b	$18, $25, $2B, $25, $2E, $C4
LNS_techs_021:
	dc.b	$1D, $25, $2B, $25, $2E, $C4
LNS_techs_022:
	dc.b	$11, $2D, $37, $25, $2B, $25, $2E, $C4
LNS_techs_023:
	dc.b	$18, $25, $37, $25, $2B, $25, $2E, $C4
LNS_techs_024:
	dc.b	$11, $29, $32, $29, $36, $25, $C4
LNS_techs_025:
	dc.b	$1D, $25, $2B, $29, $32, $29, $36, $25, $C4
LNS_techs_026:
	dc.b	$0C, $33, $30, $38, $C4
LNS_techs_027:
	dc.b	$1D, $25, $26, $33, $30, $38, $C4
LNS_techs_028:
	dc.b	$1D, $29, $2D, $3E, $39, $36, $29, $37, $C4
LNS_techs_029:
	dc.b	$0E, $36, $39, $32, $2F, $C4
LNS_techs_030:
	dc.b	$16, $2D, $31, $2D, $38, $29, $36, $C4
LNS_techs_031:
	dc.b	$1D, $2C, $2D, $32, $34, $25, $36, $33, $C4
LNS_techs_032:
	dc.b	$10, $33, $30, $37, $25, $C4
LNS_techs_033:
	dc.b	$16, $2D, $31, $2D, $38, $29, $C4
LNS_techs_034:
	dc.b	$1D, $27, $2C, $39, $38, $3E, $C4
LNS_techs_035:
	dc.b	$1D, $25, $37, $27, $2C, $39, $38, $3E, $C4
LNS_techs_036:
	dc.b	$0E, $29, $26, $25, $32, $28, $C4
LNS_techs_037:
	dc.b	$1D, $27, $2C, $32, $29, $30, $30, $25, $C4
LNS_techs_038:
	dc.b	$1D, $25, $37, $2C, $32, $29, $30, $25, $C4
LNS_techs_039:
	dc.b	$1C, $29, $37, $38, $25, $C4
LNS_techs_040:
	dc.b	$11, $2D, $36, $29, $37, $38, $25, $C4
LNS_techs_041:
	dc.b	$18, $25, $36, $29, $37, $38, $25, $C4
LNS_techs_042:
	dc.b	$1D, $25, $36, $29, $37, $38, $25, $C4
LNS_techs_043:
	dc.b	$11, $2D, $37, $25, $36, $29, $37, $38, $25, $C4
LNS_techs_044:
	dc.b	$18, $25, $37, $25, $36, $29, $37, $38, $C4
LNS_techs_045:
	dc.b	$1D, $25, $27, $36, $25, $C4
LNS_techs_046:
	dc.b	$18, $25, $37, $25, $27, $36, $25, $C4
LNS_techs_047:
	dc.b	$0B, $32, $38, $2D, $C4
LNS_techs_048:
	dc.b	$1C, $29, $3A, $29, $36, $37, $29, $36, $C4
LNS_techs_049:
	dc.b	$1C, $3D, $39, $2F, $29, $36, $C4
LNS_techs_050:
	dc.b	$12, $2D, $32, $25, $37, $C4
LNS_techs_051:
	dc.b	$17, $39, $37, $2D, $27, $25, $C4
LNS_techs_052:
	dc.b	$17, $29, $2B, $2D, $28, $C4
LNS_techs_053:
	dc.b	$1C, $3D, $39, $39, $2A, $29, $C4
LNS_techs_054:
	dc.b	$C4
LNS_techs_055:
	dc.b	$C4
LNS_techs_056:
	dc.b	$C4
LNS_techs_057:
	dc.b	$C4
LNS_techs_058:
	dc.b	$C4
LNS_techs_059:
	dc.b	$C4
LNS_techs_060:
	dc.b	$C4
LNS_techs_061:
	dc.b	$C4
LNS_techs_062:
	dc.b	$C4
LNS_techs_063:
	dc.b	$C4
LNS_enemies_000:
	dc.b	$C4
LNS_enemies_001:
	dc.b	$0C, $2D, $38, $2D, $32, $2B, $00, $0B, $32, $38, $C4
LNS_enemies_002:
	dc.b	$0B, $36, $31, $29, $28, $00, $0B, $32, $38, $C4
LNS_enemies_003:
	dc.b	$1A, $25, $32, $3E, $29, $36, $00, $0B, $32, $38, $C4
LNS_enemies_004:
	dc.b	$17, $33, $37, $35, $39, $2D, $38, $33, $C4
LNS_enemies_005:
	dc.b	$11, $2D, $2B, $25, $00, $17, $33, $37, $35, $39, $2D, $38, $33, $C4
LNS_enemies_006:
	dc.b	$11, $36, $25, $32, $28, $00, $17, $33, $37, $35, $39, $2D, $38, $33, $C4
LNS_enemies_007:
	dc.b	$1D, $34, $2D, $32, $32, $2D, $32, $2B, $00, $1D, $34, $2C, $29, $36, $29, $C4
LNS_enemies_008:
	dc.b	$10, $25, $32, $27, $3D, $00, $1D, $34, $2C, $29, $36, $29, $C4
LNS_enemies_009:
	dc.b	$20, $2D, $37, $2D, $33, $32, $00, $1D, $34, $2C, $29, $36, $29, $C4
LNS_enemies_010:
	dc.b	$10, $29, $32, $27, $29, $36, $C4
LNS_enemies_011:
	dc.b	$17, $25, $37, $38, $29, $36, $00, $10, $29, $32, $27, $29, $36, $C4
LNS_enemies_012:
	dc.b	$17, $06, $00, $10, $29, $32, $27, $29, $36, $C4
LNS_enemies_013:
	dc.b	$1A, $33, $2D, $37, $33, $32, $29, $36, $C4
LNS_enemies_014:
	dc.b	$1A, $33, $2D, $37, $33, $32, $29, $28, $00, $0B, $36, $36, $33, $3B, $C4
LNS_enemies_015:
	dc.b	$1A, $33, $2D, $37, $33, $32, $00, $10, $25, $32, $2B, $C4
LNS_enemies_016:
	dc.b	$10, $30, $3D, $2D, $32, $2B, $00, $1A, $29, $28, $36, $25, $C4
LNS_enemies_017:
	dc.b	$0D, $29, $32, $38, $2D, $34, $29, $28, $36, $25, $C4
LNS_enemies_018:
	dc.b	$11, $36, $29, $29, $28, $3D, $00, $1A, $29, $28, $36, $25, $C4
LNS_enemies_019:
	dc.b	$16, $2D, $27, $2F, $29, $36, $C4
LNS_enemies_020:
	dc.b	$10, $25, $27, $29, $00, $16, $2D, $27, $2F, $29, $36, $C4
LNS_enemies_021:
	dc.b	$1D, $2F, $39, $30, $30, $00, $16, $2D, $27, $2F, $29, $36, $C4
LNS_enemies_022:
	dc.b	$0D, $25, $36, $36, $2D, $29, $36, $C4
LNS_enemies_023:
	dc.b	$0D, $2C, $33, $2F, $2D, $32, $2B, $00, $1C, $33, $38, $C4
LNS_enemies_024:
	dc.b	$1C, $39, $37, $38, $00, $1C, $33, $38, $C4
LNS_enemies_025:
	dc.b	$21, $2C, $2D, $37, $38, $30, $29, $C4
LNS_enemies_026:
	dc.b	$13, $32, $2A, $33, $36, $31, $29, $36, $C4
LNS_enemies_027:
	dc.b	$1E, $36, $25, $27, $29, $36, $C4
LNS_enemies_028:
	dc.b	$11, $36, $25, $37, $37, $00, $15, $2D, $30, $30, $29, $36, $C4
LNS_enemies_029:
	dc.b	$11, $36, $25, $37, $37, $00, $0B, $37, $37, $25, $37, $37, $2D, $32, $C4
LNS_enemies_030:
	dc.b	$11, $36, $25, $37, $37, $00, $1D, $30, $25, $39, $2B, $2C, $38, $29, $36, $29
	dc.b	$36, $C4
LNS_enemies_031:
	dc.b	$0B, $31, $33, $29, $26, $33, $2D, $28, $C4
LNS_enemies_032:
	dc.b	$1D, $27, $2C, $30, $29, $2D, $31, $3E, $29, $30, $30, $29, $C4
LNS_enemies_033:
	dc.b	$17, $2D, $3C, $00, $0B, $31, $33, $29, $26, $25, $29, $C4
LNS_enemies_034:
	dc.b	$1A, $33, $30, $2D, $3E, $29, $2D, $C4
LNS_enemies_035:
	dc.b	$1A, $33, $30, $2D, $3E, $29, $2D, $00, $0B, $22, $C4
LNS_enemies_036:
	dc.b	$1A, $33, $30, $2D, $3E, $29, $2D, $00, $1D, $1D, $C4
LNS_enemies_037:
	dc.b	$12, $2D, $36, $39, $28, $33, $C4
LNS_enemies_038:
	dc.b	$0C, $29, $30, $27, $2C, $00, $16, $29, $29, $27, $2C, $C4
LNS_enemies_039:
	dc.b	$20, $33, $31, $2D, $38, $2D, $32, $2B, $00, $16, $29, $29, $27, $2C, $C4
LNS_enemies_040:
	dc.b	$1D, $2D, $37, $3D, $36, $25, $C4
LNS_enemies_041:
	dc.b	$0D, $2C, $36, $3D, $37, $33, $34, $25, $C4
LNS_enemies_042:
	dc.b	$12, $29, $31, $29, $36, $33, $26, $2D, $39, $37, $C4
LNS_enemies_043:
	dc.b	$0C, $25, $38, $2C, $00, $0D, $33, $3A, $29, $36, $C4
LNS_enemies_044:
	dc.b	$17, $25, $32, $00, $0D, $33, $3A, $29, $36, $C4
LNS_enemies_045:
	dc.b	$1A, $30, $25, $32, $29, $38, $00, $0D, $33, $3A, $29, $36, $C4
LNS_enemies_046:
	dc.b	$0E, $29, $25, $28, $3B, $33, $33, $28, $C4
LNS_enemies_047:
	dc.b	$0C, $30, $33, $27, $2F, $2C, $29, $25, $28, $C4
LNS_enemies_048:
	dc.b	$10, $25, $2D, $30, $39, $36, $29, $C4
LNS_enemies_049:
	dc.b	$0C, $30, $2D, $3E, $3E, $25, $36, $28, $25, $C4
LNS_enemies_050:
	dc.b	$0C, $39, $36, $32, $00, $21, $33, $30, $2A, $C4
LNS_enemies_051:
	dc.b	$10, $30, $25, $36, $29, $00, $21, $33, $30, $2A, $C4
LNS_enemies_052:
	dc.b	$1D, $29, $25, $00, $1D, $27, $2D, $37, $37, $33, $36, $37, $C4
LNS_enemies_053:
	dc.b	$1D, $29, $25, $00, $1D, $2C, $29, $25, $36, $C4
LNS_enemies_054:
	dc.b	$1D, $29, $25, $00, $1D, $2C, $29, $25, $36, $00, $16, $33, $36, $28, $C4
LNS_enemies_055:
	dc.b	$1D, $38, $25, $36, $2A, $2D, $37, $2C, $C4
LNS_enemies_056:
	dc.b	$1D, $34, $2D, $32, $32, $2D, $32, $2B, $00, $1D, $38, $25, $36, $C4
LNS_enemies_057:
	dc.b	$1D, $25, $3B, $2D, $32, $2B, $00, $1D, $38, $25, $36, $C4
LNS_enemies_058:
	dc.b	$0E, $29, $2C, $33, $C4
LNS_enemies_059:
	dc.b	$12, $33, $3E, $39, $2D, $38, $33, $00, $0E, $29, $2C, $33, $C4
LNS_enemies_060:
	dc.b	$13, $34, $34, $33, $00, $0E, $29, $2C, $33, $C4
LNS_enemies_061:
	dc.b	$15, $2D, $38, $29, $2F, $2D, $32, $28, $C4
LNS_enemies_062:
	dc.b	$1C, $29, $34, $38, $2D, $30, $29, $00, $15, $2D, $38, $29, $C4
LNS_enemies_063:
	dc.b	$15, $2D, $38, $29, $00, $0E, $36, $25, $2B, $33, $32, $C4
LNS_enemies_064:
	dc.b	$18, $29, $33, $00, $0D, $25, $3D, $38, $33, $32, $2D, $25, $C4
LNS_enemies_065:
	dc.b	$18, $29, $33, $00, $18, $2D, $30, $37, $37, $33, $32, $2D, $25, $C4
LNS_enemies_066:
	dc.b	$18, $29, $33, $00, $0C, $29, $32, $32, $29, $38, $38, $2D, $38, $29, $37, $C4
LNS_enemies_067:
	dc.b	$0B, $2D, $30, $33, $39, $36, $33, $37, $C4
LNS_enemies_068:
	dc.b	$16, $3D, $32, $3C, $C4
LNS_enemies_069:
	dc.b	$1A, $25, $32, $38, $2C, $29, $36, $25, $C4
LNS_enemies_070:
	dc.b	$1D, $25, $38, $00, $17, $25, $32, $C4
LNS_enemies_071:
	dc.b	$1D, $25, $38, $00, $0C, $33, $3D, $C4
LNS_enemies_072:
	dc.b	$1D, $25, $38, $00, $1D, $25, $38, $C4
LNS_enemies_073:
	dc.b	$17, $2D, $3E, $33, $36, $25, $32, $00, $11, $25, $31, $31, $25, $C4
LNS_enemies_074:
	dc.b	$17, $2D, $3E, $33, $36, $25, $32, $00, $1D, $2D, $2B, $31, $25, $C4
LNS_enemies_075:
	dc.b	$17, $2D, $3E, $33, $36, $25, $32, $00, $19, $31, $29, $2B, $25, $C4
LNS_enemies_076:
	dc.b	$0C, $25, $31, $26, $33, $33, $C4
LNS_enemies_077:
	dc.b	$0C, $25, $31, $26, $33, $33, $00, $1E, $3B, $2D, $2B, $C4
LNS_enemies_078:
	dc.b	$0C, $25, $31, $26, $33, $33, $00, $0E, $33, $30, $30, $C4
LNS_enemies_079:
	dc.b	$0D, $33, $33, $30, $2D, $29, $46, $07, $02, $C4
LNS_enemies_080:
	dc.b	$1D, $25, $26, $33, $27, $25, $34, $C4
LNS_enemies_081:
	dc.b	$17, $2D, $32, $29, $36, $25, $30, $33, $2B, $2D, $37, $38, $C4
LNS_enemies_082:
	dc.b	$0F, $3D, $29, $37, $33, $36, $29, $C4
LNS_enemies_083:
	dc.b	$12, $29, $25, $3A, $3D, $00, $1D, $33, $30, $28, $2D, $29, $36, $C4
LNS_enemies_084:
	dc.b	$11, $36, $25, $32, $28, $00, $0C, $39, $37, $38, $29, $36, $C4
LNS_enemies_085:
	dc.b	$0B, $36, $31, $3D, $00, $0F, $3D, $29, $C4
LNS_enemies_086:
	dc.b	$1E, $36, $25, $27, $29, $36, $00, $0C, $25, $37, $29, $C4
LNS_enemies_087:
	dc.b	$1A, $33, $30, $2D, $32, $37, $34, $29, $27, $38, $33, $36, $C4
LNS_enemies_088:
	dc.b	$20, $25, $32, $C4
LNS_enemies_089:
	dc.b	$20, $25, $32, $00, $16, $29, $25, $28, $29, $36, $C4
LNS_enemies_090:
	dc.b	$0B, $2D, $36, $29, $00, $1E, $2D, $29, $36, $C4
LNS_enemies_091:
	dc.b	$12, $39, $32, $2B, $36, $3D, $00, $0B, $34, $29, $C4
LNS_enemies_092:
	dc.b	$1C, $25, $37, $27, $25, $30, $00, $17, $33, $32, $2F, $29, $3D, $C4
LNS_enemies_093:
	dc.b	$0E, $36, $33, $30, $30, $00, $17, $33, $32, $2F, $29, $3D, $C4
LNS_enemies_094:
	dc.b	$18, $29, $33, $00, $17, $25, $31, $31, $33, $38, $2C, $C4
LNS_enemies_095:
	dc.b	$18, $29, $33, $00, $0C, $2D, $2B, $00, $18, $33, $37, $29, $C4
LNS_enemies_096:
	dc.b	$0E, $29, $3E, $33, $30, $2D, $25, $00, $17, $25, $31, $31, $33, $38, $2C, $C4
LNS_enemies_097:
	dc.b	$19, $3B, $30, $00, $0E, $29, $3E, $33, $30, $2D, $25, $C4
LNS_enemies_098:
	dc.b	$1D, $2F, $3D, $00, $1E, $2D, $25, $36, $25, $C4
LNS_enemies_099:
	dc.b	$17, $25, $30, $29, $2A, $2D, $27, $00, $0F, $3D, $29, $C4
LNS_enemies_100:
	dc.b	$0E, $2D, $36, $38, $3D, $00, $0B, $32, $2B, $33, $36, $25, $C4
LNS_enemies_101:
	dc.b	$1D, $34, $33, $2D, $30, $00, $1C, $25, $26, $26, $2D, $38, $C4
LNS_enemies_102:
	dc.b	$1D, $32, $2D, $2A, $2A, $3D, $00, $1C, $25, $26, $26, $2D, $38, $C4
LNS_enemies_103:
	dc.b	$17, $39, $37, $33, $30, $29, $C4
LNS_enemies_104:
	dc.b	$1D, $25, $2F, $33, $3A, $C4
LNS_enemies_105:
	dc.b	$17, $33, $37, $33, $30, $33, $3A, $C4
LNS_enemies_106:
	dc.b	$16, $2D, $3A, $2D, $32, $2B, $00, $0C, $30, $25, $28, $29, $C4
LNS_enemies_107:
	dc.b	$0D, $36, $3D, $00, $0C, $36, $2D, $32, $2B, $29, $36, $C4
LNS_enemies_108:
	dc.b	$0E, $29, $25, $38, $2C, $36, $33, $32, $29, $36, $C4
LNS_enemies_109:
	dc.b	$0E, $25, $36, $2F, $37, $2D, $28, $29, $C4
LNS_enemies_110:
	dc.b	$0E, $29, $25, $38, $2C, $00, $13, $32, $3A, $29, $36, $38, $29, $36, $C4
LNS_enemies_111:
	dc.b	$1D, $2C, $25, $28, $29, $00, $1D, $2C, $2D, $2A, $38, $29, $36, $C4
LNS_enemies_112:
	dc.b	$0D, $2C, $25, $33, $37, $00, $1D, $33, $36, $27, $29, $36, $29, $36, $C4
LNS_enemies_113:
	dc.b	$13, $30, $30, $39, $37, $2D, $33, $32, $2D, $37, $38, $C4
LNS_enemies_114:
	dc.b	$13, $31, $25, $2B, $2D, $33, $00, $17, $25, $2B, $29, $C4
LNS_enemies_115:
	dc.b	$0B, $36, $27, $2C, $00, $0E, $36, $25, $2B, $33, $32, $C4
LNS_enemies_116:
	dc.b	$0E, $36, $25, $2B, $33, $32, $00, $0E, $33, $39, $26, $38, $C4
LNS_enemies_117:
	dc.b	$0E, $36, $25, $2B, $33, $32, $00, $12, $25, $38, $29, $C4
LNS_enemies_118:
	dc.b	$10, $2D, $36, $29, $00, $16, $29, $31, $39, $36, $29, $37, $C4
LNS_enemies_119:
	dc.b	$1D, $38, $33, $36, $31, $00, $16, $29, $31, $39, $36, $29, $37, $C4
LNS_enemies_120:
	dc.b	$15, $2D, $32, $2B, $00, $16, $29, $31, $39, $36, $29, $37, $C4
LNS_enemies_121:
	dc.b	$0E, $25, $46, $15, $29, $31, $39, $30, $46, $1C, $25, $C4
LNS_enemies_122:
	dc.b	$1C, $39, $32, $46, $10, $2D, $32, $46, $11, $25, $C4
LNS_enemies_123:
	dc.b	$11, $2D, $46, $16, $39, $46, $24, $25, $36, $2F, $C4
LNS_enemies_124:
	dc.b	$18, $29, $2D, $46, $10, $2D, $36, $37, $38, $C4
LNS_enemies_125:
	dc.b	$0E, $25, $36, $2F, $00, $10, $25, $30, $3E, $C4
LNS_enemies_126:
	dc.b	$17, $33, $38, $2C, $29, $36, $00, $0C, $36, $25, $2D, $32, $C4
LNS_teleport_000:
	dc.b	$1D, $2F, $39, $36, $29, $C4
LNS_teleport_001:
	dc.b	$1A, $25, $37, $29, $33, $C4
LNS_teleport_002:
	dc.b	$0B, $36, $2D, $31, $25, $3D, $25, $C4
LNS_teleport_003:
	dc.b	$19, $34, $38, $25, $32, $33, $C4
LNS_teleport_004:
	dc.b	$24, $29, $31, $25, $C4
LNS_teleport_005:
	dc.b	$15, $39, $29, $36, $2D, $37, $C4
LNS_teleport_006:
	dc.b	$1A, $2D, $25, $38, $25, $C4
LNS_teleport_007:
	dc.b	$0B, $39, $2F, $26, $25, $30, $C4
LNS_teleport_008:
	dc.b	$24, $33, $37, $25, $C4
LNS_teleport_009:
	dc.b	$1C, $3D, $39, $33, $32, $C4
LNS_soundtracks_000:
	dc.b	$1A, $2C, $25, $32, $38, $25, $37, $3D, $00, $1D, $34, $36, $25, $2D, $38, $C4
LNS_soundtracks_001:
	dc.b	$1C, $29, $37, $38, $33, $36, $25, $38, $2D, $33, $32, $C4
LNS_soundtracks_002:
	dc.b	$1A, $30, $29, $25, $37, $39, $36, $29, $00, $1D, $38, $36, $29, $25, $31, $C4
LNS_soundtracks_003:
	dc.b	$0B, $28, $3A, $25, $32, $27, $29, $28, $00, $1A, $33, $37, $2D, $38, $2D, $33
	dc.b	$32, $C4
LNS_soundtracks_004:
	dc.b	$1D, $38, $29, $34, $00, $1F, $34, $C4
LNS_soundtracks_005:
	dc.b	$0C, $30, $25, $27, $2F, $3D, $00, $18, $29, $3B, $37, $C4
LNS_soundtracks_006:
	dc.b	$17, $3D, $00, $12, $33, $31, $29, $C4
LNS_soundtracks_007:
	dc.b	$1A, $36, $29, $37, $37, $39, $36, $29, $C4
LNS_soundtracks_008:
	dc.b	$1A, $36, $33, $30, $33, $2B, $39, $29, $C4
LNS_soundtracks_009:
	dc.b	$1C, $2D, $37, $29, $00, $33, $36, $00, $10, $25, $30, $30, $C4
LNS_soundtracks_010:
	dc.b	$17, $33, $3A, $29, $31, $29, $32, $38, $C4
LNS_soundtracks_011:
	dc.b	$19, $3A, $29, $36, $C4
LNS_soundtracks_012:
	dc.b	$1D, $29, $27, $36, $29, $38, $00, $21, $25, $3D, $37, $C4
LNS_soundtracks_013:
	dc.b	$1A, $36, $33, $31, $2D, $37, $29, $28, $00, $17, $3D, $37, $38, $29, $36, $3D
	dc.b	$C4
LNS_soundtracks_014:
	dc.b	$1E, $2C, $29, $00, $1A, $30, $25, $27, $29, $00, $33, $2A, $00, $0E, $29, $25
	dc.b	$38, $2C, $C4
LNS_soundtracks_015:
	dc.b	$1D, $2D, $30, $29, $32, $38, $00, $24, $33, $32, $29, $C4
LNS_soundtracks_016:
	dc.b	$0F, $3C, $27, $2D, $38, $2D, $32, $2B, $00, $1E, $33, $3B, $32, $C4
LNS_soundtracks_017:
	dc.b	$20, $2D, $33, $30, $25, $38, $2D, $33, $32, $C4
LNS_soundtracks_018:
	dc.b	$1A, $33, $3B, $29, $36, $C4
LNS_soundtracks_019:
	dc.b	$1F, $32, $28, $29, $36, $C4
LNS_soundtracks_020:
	dc.b	$0F, $3C, $27, $30, $25, $2D, $31, $C4
LNS_soundtracks_021:
	dc.b	$18, $29, $3A, $29, $36, $00, $0E, $36, $29, $25, $31, $2D, $32, $2B, $C4
LNS_jobs_000:
	dc.b	$0B, $2B, $29, $32, $38, $C4
LNS_jobs_001:
	dc.b	$14, $33, $26, $30, $29, $37, $37, $C4
LNS_jobs_002:
	dc.b	$12, $39, $32, $38, $29, $36, $C4
LNS_jobs_003:
	dc.b	$0E, $33, $27, $38, $33, $36, $C4
LNS_jobs_004:
	dc.b	$1D, $27, $2C, $33, $30, $25, $36, $C4
LNS_jobs_005:
	dc.b	$0D, $33, $39, $32, $38, $29, $36, $2C, $39, $32, $38, $29, $36, $C4
LNS_jobs_006:
	dc.b	$14, $39, $32, $2F, $00, $0E, $29, $25, $30, $29, $36, $C4
LNS_jobs_007:
	dc.b	$1E, $2C, $2D, $29, $2A, $C4
	even
